jbossApp:
    image: tutum/jboss
    volumes:
        - /war:/jboss-as-7.1.1.Final/standalone/deployments
    net: bridge
    links:
        - db
    ports:        
        - "8080:8080"    
        - "9990:9990"    

db:
    image: klevo/percona
    volumes:
        - /var/lib/mysql:/var/lib/mysql
    expose:
        - "3306:3306"
    


