jbossApp:
    image: tutum/jboss
    #volumes:
    #    - /war_file:/war_file
    links:
        - db
    ports:        
        - "8080:8080"    
        - "9990:9990"    

db:
    image: klevo/percona
    #environment:
    #    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
        - /var/lib/mysql:/var/lib/mysql
    expose:
        - "3306:3306"
    


