jboss:
    #container_name: jboss-app
    image: ubuntu:trusty
    volumes:
        - /war_file:/war_file
    links:
        - mysql
    expose:        
        - "8080"    

mysql:
    #container_name: data-store
    image: mysql/mysql-server
    environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    working_dir: "/var/www"
    volumes:
        - /dbdata:/var/lib/mysql
    expose:
        - "3306"
    


