mysql:
    container_name: data-store
    image: mysql/mysql-server
    working_dir: "/var/www"
    volumes:
        - /var/lib/mysql:/var/lib/mysql    
    volumes_from:
        - jboss
    links:
        - mysql
    expose:
        - "3306"

